/**
 * Reader-safe re-export of the AMBIGUOUS_NAMES surface-key set.
 *
 * The full AMBIGUOUS_NAMES config lives in `./annotator.ts` and pulls in
 * server-only modules (better-sqlite3 via the entity DB). This file
 * exposes ONLY the lowercase surface keys ("james", "simon", "mary"…)
 * so the client-side EntityLayerProvider can filter annotations whose
 * surface form has multiple possible referents — preventing the
 * single-annotation-spread bug where the LLM correctly tags the first
 * "James" (e.g. brother of Jesus) and the renderer's surface-form regex
 * propagates that tag onto every other "James" in prose, including
 * disambiguated mentions like "the apostle James son of Zebedee".
 *
 * Adding a new ambiguous name: edit `annotator.ts` only — this file's
 * KEYS array is regenerated by hand to mirror it. We don't import the
 * AMBIGUOUS_NAMES const directly because the client bundle would then
 * pull in better-sqlite3.
 */

export const AMBIGUOUS_NAME_KEYS: ReadonlySet<string> = new Set([
  'herod',
  'james',
  'mary',
  'joseph',
  'simon',
  'john',
  'judas',
]);

/**
 * Returns true when the (case-insensitive) surface form has multiple
 * possible entity referents and should NOT be rendered with an inline
 * annotation tooltip. The surrounding prose context disambiguates;
 * a wrong tooltip is worse than no tooltip.
 */
export function isAmbiguousSurface(surface: string): boolean {
  return AMBIGUOUS_NAME_KEYS.has(surface.trim().toLowerCase());
}
